{
 "title": "Pulsar / Bookkeeper read cache",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Reads to disk per read op",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(bookie_readahead_batch_count_count[1m])) by (instance) + sum(rate(bookie_readahead_batch_count_sum[1m])) by (instance)) / sum(rate(bookie_read_entry_count[1m])) by (instance)"
    }
   ]
  },
  {
   "title": "Failed read request rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bookkeeper_server_READ_ENTRY_REQUEST_count{success=\"false\"}[1m])) by (instance)"
    }
   ]
  },
  {
   "title": "Read request rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bookkeeper_server_READ_ENTRY_REQUEST_count[1m])) by (instance)"
    }
   ]
  },
  {
   "title": "Bookie read throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bookie_READ_BYTES[1m])) by (instance)"
    }
   ]
  },
  {
   "title": "Bookie read operation rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bookkeeper_server_READ_ENTRY_count[1m])) by (instance)"
    }
   ]
  },
  {
   "title": "Bookie read cache size 1 minute increase",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(bookie_read_cache_size[1m])"
    }
   ]
  },
  {
   "title": "Bookie read cache hits",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bookie_read_cache_hits_count[1m])) by (instance)"
    }
   ]
  },
  {
   "title": "Bookie read cache misses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bookie_read_cache_misses_count[1m])) by (instance)"
    }
   ]
  },
  {
   "title": "Cache miss to hit ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(bookie_read_cache_misses_count[1m])) by (instance) / sum(irate(bookie_read_cache_hits_count[1m])) by (instance)) * 100"
    }
   ]
  }
 ]
}