{
 "title": "Pulsar / Broker Cache By Broker",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "broker",
    "query": {
     "query": "label_values(pulsar_ml_AddEntryBytesRate, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "In/Out Rate vs Cache Hit/Miss Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pulsar_ml_cache_hits_rate{instance=~\"$broker\"}) ",
     "legendFormat": "Cache Hit "
    },
    {
     "expr": "sum(pulsar_ml_cache_misses_rate{instance=~\"$broker\"})",
     "legendFormat": "Miss Rate"
    },
    {
     "expr": "sum(avg(pulsar_rate_in{instance=~\"$broker\"}) by (topic)) ",
     "legendFormat": "Rate In"
    },
    {
     "expr": "sum(avg(pulsar_rate_out{instance=~\"$broker\"}) by (topic)) ",
     "legendFormat": "Rate Out"
    }
   ]
  },
  {
   "title": "Cache Hit Percentage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_ml_cache_hits_rate{instance=~\"$broker\"}) / (sum(pulsar_ml_cache_hits_rate{instance=~\"$broker\"}) + sum(pulsar_ml_cache_misses_rate{instance=~\"$broker\"})) * 100",
     "legendFormat": "Cache Hit %"
    }
   ]
  },
  {
   "title": "Cache Miss Rate by Broker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pulsar_ml_cache_misses_rate{instance=~\"$broker\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_ml_cache_hits_rate{instance=~\"$broker\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hits Throughput by Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_ml_cache_hits_throughput{instance=~\"$broker\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Misses Throughput by Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_ml_cache_misses_throughput{instance=~\"$broker\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Size By Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_ml_cache_used_size{instance=~\"$broker\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Evictions by Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_ml_cache_evictions{instance=~\"$broker\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}