{
 "title": "Pulsar / Namespace",
 "tags": [ "pulsar" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "pulsar_producers_count{cluster=~\".+\"}"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "pulsar_producers_count{cluster=\"$cluster\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Local publish rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "msg/s" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_rate_in{cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (cluster, namespace)",
     "legendFormat": "{{cluster}} - {{namespace}}"
    }
   ]
  },
  {
   "title": "Local delivery rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "msg / s" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_rate_out{cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (cluster, namespace)",
     "legendFormat": "{{cluster}} - {{namespace}}"
    }
   ]
  },
  {
   "title": "Local publish throughput (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_throughput_in{cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (cluster, namespace)",
     "legendFormat": "{{cluster}} - {{namespace}}"
    }
   ]
  },
  {
   "title": "Local delivery throughput (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_throughput_out{cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (cluster, namespace)",
     "legendFormat": "{{cluster}} - {{namespace}}"
    }
   ]
  },
  {
   "title": "Topics - Producers - Subscriptions - Consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_topics_count{cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "topics"
    },
    {
     "expr": "sum(pulsar_producers_count{cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "producers"
    },
    {
     "expr": "sum(pulsar_subscriptions_count{cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "subscriptions"
    },
    {
     "expr": "sum(pulsar_consumers_count{cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "consumers"
    }
   ]
  },
  {
   "title": "Local backlog",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_msg_backlog{cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (cluster, namespace)",
     "legendFormat": "{{cluster}} - {{namespace}}"
    }
   ]
  },
  {
   "title": "Storage Write Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "msg / s" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_storage_write_latency_le_0_5{cluster=~\"$cluster\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "0 - 0.5 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_1{cluster=~\"$cluster\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "0.5 - 1 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_5{cluster=~\"$cluster\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "1 - 5 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_10{cluster=~\"$cluster\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "5 - 10 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_20{cluster=~\"$cluster\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "10 - 20 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_50{cluster=~\"$cluster\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "20 - 50 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_100{cluster=~\"$cluster\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "50 - 100 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_200{cluster=~\"$cluster\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "100 - 200 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_1000{cluster=~\"$cluster\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "200 ms - 1 s"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_overflow{cluster=~\"$cluster\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "> 1 s"
    }
   ]
  },
  {
   "title": "Storage Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_storage_size{cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "$namespace"
    }
   ]
  },
  {
   "title": "Incoming replication rate | any → $cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "msg / s" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_replication_rate_in{cluster=~\"$cluster\", namespace=~\"$namespace\", remote_cluster!=\"local\"}) by (cluster, remote_cluster)",
     "legendFormat": "{{remote_cluster}} → {{cluster}}"
    }
   ]
  },
  {
   "title": "Outgoing replication rate | $cluster → any",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "msg / s" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_replication_rate_out{cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "{{cluster}} → {{remote_cluster}}"
    }
   ]
  },
  {
   "title": "Replication backlog | $cluster → any",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "messages" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_replication_backlog{cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (cluster, remote_cluster)",
     "legendFormat": "{{cluster}} → {{remote_cluster}}"
    }
   ]
  },
  {
   "title": "Storage entry size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "msg / s" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_entry_size_le_128{cluster=~\"$cluster\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "< 128 bytes"
    },
    {
     "expr": "sum(pulsar_entry_size_le_512{cluster=~\"$cluster\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "< 512 bytes"
    },
    {
     "expr": "sum(pulsar_entry_size_le_1_kb{cluster=~\"$cluster\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "< 1 KB"
    },
    {
     "expr": "sum(pulsar_entry_size_le_2_kb{cluster=~\"$cluster\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "< 2 KB"
    },
    {
     "expr": "sum(pulsar_entry_size_le_4_kb{cluster=~\"$cluster\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "< 4 KB"
    },
    {
     "expr": "sum(pulsar_entry_size_le_16_kb{cluster=~\"$cluster\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "< 16 KB"
    },
    {
     "expr": "sum(pulsar_entry_size_le_100_kb{cluster=~\"$cluster\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "< 100 KB"
    },
    {
     "expr": "sum(pulsar_entry_size_le_1_mb{cluster=~\"$cluster\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "< 1 MB"
    },
    {
     "expr": "sum(pulsar_entry_size_overflow{cluster=~\"$cluster\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "> 1 MB"
    }
   ]
  },
  {
   "title": "Storage Write Rate",
   "type": "graph",
   "description": "Rate of writes into storage (can be lower than publish rate, when batching is enabled)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "entry / s" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_storage_write_rate{cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "$namespace"
    }
   ]
  },
  {
   "title": "Storage read entry rate",
   "type": "graph",
   "description": "Reads from bookies",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "entries / s" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_storage_read_rate{cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "read rate"
    }
   ]
  }
 ]
}